<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreUserRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $user = $this->route('user', null);
        $id = $user ? $user->id : null;
        return [
            'name' => 'required',
            'email' => "required|string|email|max:255|unique:users,email,$id,id,deleted_at,NULL",
            'avatar' => 'required',
            'password' => $id ? '' : 'required' . '|confirmed|min:8'
            //{{REQUEST_RULES_NOT_DELETE_THIS_LINE}}
        ];
    }

    //    public function messages()
    //	{
    //		return parent::messages(); // TODO: Change the autogenerated stub
    //	}
}
