<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreUserRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $id = $this->route('id', NULL);
        return [
//			'name' => 'required|string|max:255',
			'email' => "required|string|email|max:255|unique:users,email,$id,id,deleted_at,NULL",
//			'email' => 'required|string|email|max:255|unique:users,email,NULL,deleted_at',
//			'password' => 'required|string|min:6|confirmed',
        ];
    }

//    public function messages()
//	{
//		return parent::messages(); // TODO: Change the autogenerated stub
//	}
}
